spring.application.name=JobApplicationApp
spring.datasource.url=jdbc:mysql://localhost:3306/vacantes
spring.datasource.username=root
spring.datasource.password=Sergiolo2007.

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true